config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users
  get 'home/index'

  get '/'=>'home#index'

  post '/create'=>'home#create'

  post '/like'=>'home#like'

  post '/edit'=>'home#edit'

  post '/edit_tweet'=>'home#edit_tweet'

  post '/delete'=>'home#delete'

  get '/search'=>'home#search'

  post '/follow'=>'home#follow'

  get '/rate'=>'home#rate'

  get '/user'=>'home#user'

  post '/rate_submit'=>'home#rate_submit'

  get '/view_feedback'=>'home#view_feedback'


  post '/create_tweet_remote' => 'home#create_tweet_remote'

  get '/autocomplete_user_email' => 'home#autocomplete_user_email'
  

  namespace :api do
     namespace :v1 do
       post '/sign_in' => 'users_api#sign_in'
     end
   end
 
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user
end

app/models/following.rb
class Following < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,:confirmable

  has_many:tweets; 
  mount_uploader :avatar, AvatarUploader
        
end

app/controllers/api/v1/users_api_controller.rb
module Api
  module V1
    class UsersApiController < ::ApiController

      def sign_in
        email = params["email"]
        password = params["password"]
        user = User.find_by_email(email)
        if user
          if user.valid_password? password
            data = Hash.new
            data["access_token"] = user.access_token
            return response_data(data, "Signed In", 200)

          else
            return response_data({}, "Password Invalid", 200)

          end

        else
          return response_data({}, "User doesn't exist", 200)


        end
        return response_data({}, "Signed In", 200)
      end

    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
 
   def response_data(data, message, status, error: nil, disabled: false, update: false, params: {})
     result = Hash.new
    result[:data]  = data
     result[:message] = message
     result[:status] = status
     result[:error] = error
     result[:disabled] = disabled
     result[:update] = update
     render json: result, params: params, status: status
   end
 end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  autocomplete :user, :email


  def index
  	 # @tweet=Tweet.all
    @tweet = Tweet.includes(:user).all.order(created_at: :desc).limit(50)
  end

  def create
    # byebug
  	@content=params[:content];
    if @content.length>0
  	@tweet=current_user.tweets.create(:content=>@content);
    end
    # Usernotifier.create_tweet(@current_user).deliver_now!
    respond_to do |format|
      format.js{

      }
    end
  end

  def create_tweet_remote
    content=params[:content];
    @tweet=current_user.tweets.create(:content=>content);
    Usernotifier.create_tweet(@current_user).deliver_now!
    respond_to do |format|
            format.js{

              }
    end
  end

  def like
    tweet_id=params[:tweet_id];
    like=Like.where(:user_id=>current_user.id,:tweet_id=>tweet_id).first;
    if like
      like.destroy;  
    else
      Like.create(:user_id=>current_user.id,:tweet_id=>tweet_id);
    end
    return redirect_to '/';
  end  

  def edit
  tweet_id=params[:tweet_id];
  @tweet_id=tweet_id
  end

  def edit_tweet
    tweet_id=params[:tweet_id]
    cont=params[:content]
    tweet=Tweet.where(:id=>tweet_id).first;
    tweet.content=cont;
    tweet.save;
    print "tweet content is #{tweet.content}"
    return redirect_to '/'

  end

  def delete
  tweet_id=params[:tweet_id];
  tweet=Tweet.find_by_id(tweet_id);
  tweet.destroy;
  return redirect_to '/';
  end
  
  def search
    email=params[:email]
    @user=User.find_by_email(email);
    if !@user
    return redirect_to '/'      
    end
    
  end

  def follow
    user_id=params[:user_id]
    if !Following.where(:following_id=>user_id,:follower_id=>current_user.id).first
      Following.create(:following_id=>user_id,:follower_id=>current_user.id)
    else
      following=Following.where(:following_id=>user_id,:follower_id=>current_user.id).first
      following.destroy
    end
    return redirect_to '/'
  end

 def rate
 end
 
 def rate_submit
  name=params[:Name]
  description=params[:description]
  if !Feedback.find_by_user_id(current_user.id)
  Feedback.create(:user_id=>current_user.id,:name=>name,:description=>description);
  end
   return redirect_to '/'

 end

 def view_feedback
 end

def user
  @user=User.all
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_tweet.html.erb
<% if tweet.user_id==current_user.id%>
	
<div class="tweet">

<div class="image_left">
	<img src="https://avatars1.githubusercontent.com/u/25134359?v=3&u=a4831520044d7fe564cc9557f9d0e155dd29bdbe&s=400">
</div>

<div class="right_content">
<%user=User.where(:id=>tweet.user_id).first%>
<%= user.email%>
<div class="time"><%= tweet.created_at.to_formatted_s(:short)%>	</div>
<br>

<%= tweet.content%><br>

<div class="reaction">
<% if countlike=Like.where(:tweet_id=>tweet.id)%>
<%= countlike.count%>
<%end%>

<%if !Like.where(:user_id=>current_user.id,:tweet_id=>tweet.id).first%>
   <%= link_to "Like", url_for(controller: :home, action: :like, tweet_id: tweet.id), method: :post %> 
<%else%>
<%= link_to "Unlike", url_for(controller: :home, action: :like, tweet_id: tweet.id), method: :post %> 
<%end%>

<% if current_user.id==tweet.user_id%>
	<%= link_to "Edit", url_for(controller: :home, action: :edit, tweet_id: tweet.id), method: :post %> 
<%= link_to "Delete", url_for(controller: :home, action: :delete, tweet_id: tweet.id), method: :post %> 
<%end%>
	
</div>
</div>

</div>
<%end%>


<% follow=Following.where(:follower_id=>current_user.id)%>
<% follow.each do |follow|%>
<% if follow.following_id==tweet.user_id&&tweet.user_id!=current_user.id%>

<div class="tweet">

<div class="image_left">
	<img src="https://avatars1.githubusercontent.com/u/25134359?v=3&u=a4831520044d7fe564cc9557f9d0e155dd29bdbe&s=400">
</div>

<div class="right_content">
<%user=User.where(:id=>tweet.user_id).first%>
<%= user.email%>
<div class="time"><%= tweet.created_at.to_formatted_s(:short)%>	</div>
<br>

<%= tweet.content%><br>

<div class="reaction">
<% if countlike=Like.where(:tweet_id=>tweet.id)%>
<%= countlike.count%>
<%end%>

<%if !Like.where(:user_id=>current_user.id,:tweet_id=>tweet.id).first%>
   <%= link_to "Like", url_for(controller: :home, action: :like, tweet_id: tweet.id), method: :post %> 
<%else%>
<%= link_to "Unlike", url_for(controller: :home, action: :like, tweet_id: tweet.id), method: :post %> 
<%end%>

<% if current_user.id==tweet.user_id%>
	<%= link_to "Edit", url_for(controller: :home, action: :edit, tweet_id: tweet.id), method: :post %> 
<%= link_to "Delete", url_for(controller: :home, action: :delete, tweet_id: tweet.id), method: :post %> 
<%end%>
	
</div>
</div>

</div>

<%end%>
	
<%end%>

 <style type="text/css">
 	img{
 		width: 100px;
 		height: 100px;
 	}
 </style>

app/views/home/create.js.erb
<% puts "hello"%>


<% puts "@content.length"%>
console.log(<%= @content.length%>);

var error=true;
<% if(@content.length>0) %>
    error=false;
<% end %>

console.log(error)


if (error==true){
    noty({text: "Tweet cannot be blank", theme: "relax", type: 'failure', layout: 'topRight'});
}
else{
    noty({text: "Successfully Created Tweet", theme: "relax", type: 'success', layout: 'topRight'});
}

app/views/home/create_tweet_remote.js.erb
$("#tweets").prepend("<%= escape_javascript(render 'tweet', :tweet => @tweet) %>");

app/views/home/edit.html.erb
<%= form_tag '/edit_tweet' do%>
<%= hidden_field_tag :tweet_id, @tweet_id %>
<%= text_area_tag :content,@content,:size =>"80x4", :placeholder => 'Add your Story Here'%><br>
<%= submit_tag 'Tweet'%>
<%end%>

app/views/home/index.html.erb
<div class="create_tweet">
  <%= form_tag '/create',remote: true do %>
<%= text_area_tag :content,@content,:size =>"80x4", :placeholder => 'Add your Story Here'%><br>
<%= submit_tag 'Tweet'%>
<span id="letter"></span>
<%end%>
</div>
<br>


<div class="search">
<%= form_tag '/search',:method => :get do%>
      <%=   autocomplete_field_tag 'email', '', autocomplete_user_email_path, :size => 20 %>
      <%= submit_tag 'search'%>
<%end%>
</div>




<% if @tweet%>
    <ol>
	<% @tweet.each do |tweet|%>
	<li><%= render 'tweet',:tweet=>tweet%></li>
	<%end%>
	</ol>
<%end%>

app/views/home/rate.html.erb
<%= form_tag '/rate_submit' do%>
<%= text_field_tag :Name,@content,:placeholder => 'Name'%><br><br>
<%= text_area_tag :description,@description,:placeholder => 'Add Your Experience'%><br>

<%= submit_tag 'submit'%>
<%end%>

app/views/home/search.html.erb
<div class="user">
	
<% if @user.id!=current_user.id%>
<%= @user.email%>
<%if !Following.where(:following_id=>@user.id,:follower_id=>current_user.id).first%>
      <%= link_to "Follow", url_for(controller: :home, action: :follow, user_id: @user.id), method: :post %>
    <%else   %>
       <%= link_to "UnFollow", url_for(controller: :home, action: :follow, user_id: @user.id), method: :post %>
<%end%>

<%end%>

<br><br><br><hr>
<h1>User List </h1>
<ol>

<% user=User.all%>
<% user.each do |user|%>
<%if user.id!=current_user.id%>
<li><%= user.email%></li>
<%end%>
<%end%>

</div>

app/views/home/user.html.erb
<div class="user"><ol>
<% @user.each do |user|%>
<%if user.id!=current_user.id%>
<li><%= user.email%></li>

<%if !Following.where(:following_id=>user.id,:follower_id=>current_user.id).first%>
      <%= link_to "Follow", url_for(controller: :home, action: :follow, user_id: user.id), method: :post %>
    <%else   %>
       <%= link_to "UnFollow", url_for(controller: :home, action: :follow, user_id: user.id), method: :post %>
    <%end%>
<br><br>
<%end%>
<%end%>
</ol>
</div>

app/views/home/view_feedback.html.erb
<h1>Thanku For Feedback...... </h1>

<% feedback=Feedback.find_by_user_id(current_user.id)%>
<%= "name : #{feedback.name}"%><br>
<%= "description :  #{feedback.description}"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="left">
  <a href="/"><i class="fa fa-home" aria-hidden="true">Home</i></a>
   </div>
  <div class="mid">
  <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
  </div>
 
  <div class="right">
    <% if current_user %>
        <div class="name">
        <%= current_user.name%></div>
        <div class="logout"><%= link_to 'logout', destroy_user_session_path, method: :delete %></div>
        <%else%>
        <a href="/users/sign_in"><i class="fa f-sign-in" aria-hidden="true">Login</i></a>
        <a href="/users/sign_up"><i class="fa fa-user-plus" aria-hidden="true">Signup</i></a>

    <% end %>
  </div>
	
</header>

<section id="mainSection" id="top">
  <aside id="mainAside">
  <% if user_signed_in?%>
  <div class="pankaj">
    <div class="img">
  <img src="https://avatars1.githubusercontent.com/u/25134359?v=3&u=a4831520044d7fe564cc9557f9d0e155dd29bdbe&s=400">
</div>
<div class="follower">
<h4><%= current_user.name%></h4><br>
  <a href="/user"><h4><%= Following.where(:follower_id=>current_user.id).length%> Following</h4></a><br>
  <a href="/user"><h4><%= Following.where(:following_id=>current_user.id).length%> Follower</h4></a><br>
</div>
  </div>
  <%end%>
  </aside>
  <main id="mainMain"><%= yield %></main>
</section>
<!-- <div class="floatingTop"><a href="#top" id="toTop">^ </a></div> -->

<footer>
<div class="copyright">@copyright</div>
<%if user_signed_in?%>
  <a  href="/rate">Rate Me!</a>
  <a  href="/view_feedback">Already Rated!</a>
<%end%>
</footer>

</body>
</html>

app/views/usernotifier/create_tweet.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
    </head>
  <body>
    <h1>Thanks for Creating New Tweet, <%= @user.name %>!!!</h1>
    <p>Thanks have A Great Day</p>
  </body>
</html>